#!/bin/sh
#Devin Cote-Munroe // GNU-GPL3

#define users
echo
echo
	    echo - "Input Username and press enter. Press CTRL-D to stop loop"
while read LINE
	do
	    USERS+=( $LINE )
	done

#sshport
read  -p 'Enter Port Number: ' PORT

## some vars
SMART="file"
MDADM="file2"
SSH="sshfile"

## YES CHARLES, I STOLE THIS NEXT ONE FROM YOU. TATERS GON TATE.
NEWPASS=`dd if=/dev/urandom bs=1 count=32 2>/dev/null | base64 | rev | cut -b 2- | rev | awk '{print substr($0,2,12)}'`
NEWPASS2=`dd if=/dev/urandom bs=1 count=32 2>/dev/null | base64 | rev | cut -b 2- | rev | awk '{print substr($0,2,12)}'`

# adduser1 to system with new password, wheel and allowusers in
for i in ${USERS[@]};
	do echo $i
     	    adduser -G wheel $i
     	    echo ${NEWPASS[@]} | passwd $i --stdin
	    echo "AllowUsers $i" >> $SSH 
        echo
	    echo "User $i created and authorized for ssh with pass ${NEWPASS[@]}"
	done;
sleep 1
	echo
	    echo -e "DON'T FORGET TO UPDATE PRIME"
	echo 
	echo
sleep 1
		# Change /etc/smartd.conf
if [ -f "$SMART" ];

	echo
	    echo -e "Changes made to smartd.conf"
	echo
	else
	echo
	    echo -e "Cannot Find File smartd.conf"
	echo
fi
sleep 1
		#  Change /etc/mdadm.conf
if [ -f "$MDADM" ];
	then 
	    sed -i s/root/support@netelligent.ca/g $MDADM
	echo
	    echo -e "Changes made to mdadm.conf"
	echo
	else
	echo
	    echo -e "Cannot Find File mdadm.conf"
	echo
fi
sleep 1
		#change the ssh port
if [ -f "$SSH" ];
	then
	    sed -i s/'#Port 22'/"Port $PORT"/g $SSH
	echo
	    echo -e "SSH Port Changed to '$PORT'"
	echo
fi
